version: '3.0'
services:
  db:
    container_name: "mclinkdb"
    image: mclinktreedb
    build:
     context: db/.
    environment:
      MYSQL_DATABASE: mclinktree
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
     - "3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/init.sql
  mclinktree_back:
    depends_on:
      - db
    image: mclinktree
    build:
      context: .
    ports:
      - "8080:8080"
  mclinktree_front:
    depends_on:
      - db
      - mclinktree_back
    image: mclinktreefront
    build:
      context: front-end/.
    ports:
      - '80:80'
volumes:
    db_data: