// <auto-generated />
using System;
using McLinkTree;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace McLinkTree.Migrations
{
    [DbContext(typeof(McLinkTreeContext))]
    [Migration("20210306193130_AddRelationshipLinkToCategoriaLink")]
    partial class AddRelationshipLinkToCategoriaLink
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("McLinkTree.Models.CategoriaLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime");

                    b.Property<string>("Ico")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Posicao")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_CategoriaLink");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasName("IDX_UniqueCategoria");

                    b.ToTable("CategoriaLink");
                });

            modelBuilder.Entity("McLinkTree.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCategoriaLink")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UrlLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK_Link");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasName("IDX_UniqueLink");

                    b.HasIndex("IdCategoriaLink");

                    b.ToTable("Link");
                });

            modelBuilder.Entity("McLinkTree.Models.Link", b =>
                {
                    b.HasOne("McLinkTree.Models.CategoriaLink", null)
                        .WithMany()
                        .HasForeignKey("IdCategoriaLink")
                        .HasConstraintName("FK_Link_CategoriaLink")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
