// <auto-generated />
using System;
using McLinkTree;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace McLinkTree.Migrations
{
    [DbContext(typeof(McLinkTreeContext))]
    partial class McLinkTreeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("McLinkTree.Models.CategoriaLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime");

                    b.Property<string>("Ico")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Posicao")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_CategoriaLink");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasName("IDX_UniqueCategoria");

                    b.ToTable("CategoriaLink");
                });

            modelBuilder.Entity("McLinkTree.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CategoriaLinkId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("DtAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DtInclusao")
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UrlLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK_Link");

                    b.HasIndex("CategoriaLinkId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasName("IDX_UniqueLink");

                    b.ToTable("Link");
                });

            modelBuilder.Entity("McLinkTree.Models.Link", b =>
                {
                    b.HasOne("McLinkTree.Models.CategoriaLink", null)
                        .WithMany("Links")
                        .HasForeignKey("CategoriaLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
